- name: Deploy on OpenStack
  hosts: localhost
  vars:
    ansible_host_key_checking: false
  gather_facts: false
  tasks:
  - name: Deploy an instance
    os_server:
      state: present
      name: webserver_public
      image: cirros
      key_name: admin
      wait: yes
      flavor: tempest1
      auto_floating_ip: yes
      network: public
      meta:
        hostname: webserver.localdomain